---
params:
  branch: "default"
---


```{r}
# params <- list(branch = "kindred")
```

```{r}
branch <- params$branch

statement <- glue::glue_sql("SELECT * from customers
                             WHERE branch == {branch}", 
                            .con = db)
                             
mydata <- DBI::dbGetQuery(conn = db,
                          statement = statement) %>% 
  dplyr::arrange(desc(interest_income))
```

## Top Customers by State
```{r}

final_kable  <- mydata %>% # dplyr::group_by(group) %>%
  dplyr::select(CIF, Customer = cust_name, `Interest Income` = interest_income) %>%
  dplyr::mutate('Interest Income' = scales::dollar(`Interest Income`)) %>% 
  # gt::gt()
  knitr::kable("latex", booktabs = T, longtable = T, align = c("l","r", "r")) %>%

 kableExtra::kable_styling(
    latex_options = c("scale_down"),
    position = "left", full_width = T
  )  %>% 
 kableExtra::kable_styling(font_size = 12) 

  
  # kableExtra::row_spec(5, bold = T) %>% 
  # kableExtra::row_spec(8, bold = T) %>% 
  # kableExtra::row_spec(9, bold = T) %>% 
  # kableExtra::row_spec(12, bold = T) %>% 
  # kableExtra::row_spec(13, bold = T) %>% 
  # kableExtra::row_spec(17, bold = T) %>% 
  # kableExtra::row_spec(18, bold = T) %>% 

  # kableExtra::pack_rows(group_label = "Interest Income", start_row = 2, end_row = 5) %>% 
  # kableExtra::pack_rows(group_label = "Interest Expense", start_row = 6, end_row = 9) %>% 
  # kableExtra::pack_rows(group_label = "Noninterest Income", start_row = 10, end_row = 13) %>% 
  # kableExtra::pack_rows(group_label = "Noninterest Expense", start_row = 14, end_row = 17)

final_kable
```





```{r}
# now for a map

# get state data
states <- sf::st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))

# combine 
final <- mydata %>% 
  dplyr::left_join(states, by = c("state" = "ID"))

```

### Top Customers by State - Total Interest Income

```{r}
ggplot() +
  geom_sf(data = final$geom, aes(fill = final$interest_income)) +
  scale_fill_viridis_c(trans = "sqrt", alpha = .7) +
  labs(fill='Interest Income') + 
  theme_void()
```

